import { useCallback, useEffect, useRef, useState } from 'react';
const clean = (value) => Number.isFinite(value) ? value : null;
export function useMappingSession() {
  const [active, setActive] = useState(false); const [samples, setSamples] = useState([]); const [startedAt, setStartedAt] = useState(null);
  const ref = useRef([]); const last = useRef(0); const location = useRef(null);
  const add = useCallback((sample) => { const t = Date.now(); if (t - last.current < 100) return; last.current = t; ref.current = [...ref.current, { t, ...sample, location: location.current }].slice(-20000); setSamples(ref.current); }, []);
  useEffect(() => { if (!active) return; const motion = (e) => add({ type: 'motion', acceleration: e.acceleration && { x: clean(e.acceleration.x), y: clean(e.acceleration.y), z: clean(e.acceleration.z) }, rotationRate: e.rotationRate && { alpha: clean(e.rotationRate.alpha), beta: clean(e.rotationRate.beta), gamma: clean(e.rotationRate.gamma) } }); const orient = (e) => add({ type: 'orientation', orientation: { alpha: clean(e.alpha), beta: clean(e.beta), gamma: clean(e.gamma), absolute: e.absolute === true } }); const watch = navigator.geolocation?.watchPosition?.((p) => { const c = p.coords; location.current = { latitude: c.latitude, longitude: c.longitude, accuracy: c.accuracy }; add({ type: 'location' }); }, () => {}, { enableHighAccuracy: true, maximumAge: 1000, timeout: 5000 }); window.addEventListener('devicemotion', motion); window.addEventListener('deviceorientation', orient); return () => { window.removeEventListener('devicemotion', motion); window.removeEventListener('deviceorientation', orient); if (watch != null) navigator.geolocation?.clearWatch?.(watch); }; }, [active, add]);
  const start = useCallback(() => { ref.current = []; setSamples([]); setStartedAt(Date.now()); setActive(true); }, []); const stop = useCallback(() => setActive(false), []);
  const download = useCallback(() => { const payload = { schemaVersion: 1, startedAt, endedAt: Date.now(), samples: ref.current }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `supernav-mapping-${startedAt || Date.now()}.json`; a.click(); URL.revokeObjectURL(url); }, [startedAt]);
  return { active, samples, start, stop, download };
}
