import { useState } from 'react';
import Icon from './Icon';
import IconSprite from './IconSprite';

const tabs = ['השוואת מחירים', 'דילים', 'השוואה מעמיקה', 'קניות קודמות'];
const icons = ['tag', 'star', 'chart', 'receipt'];

function DealsPreview() { return <div className="compare-preview-deals"><div className="deals-preview-header"><div><span className="compare-preview-eyebrow">דילים לפי מחירים רשמיים</span><h2>איפה הסל שלך משתלם יותר?</h2></div><span className="compare-preview-save"><Icon name="check" /> מקור מאומת</span></div><p className="deals-preview-note">דילים עם תאריך תוקף ומקור רשמי בלבד.</p><div className="deals-preview-list"><article><strong>חלב 3% תנובה</strong><span>רמי לוי · רמת גן<br /><small>בתוקף: 05/09/2026–12/09/2026</small></span><b>₪12.90</b><em>חיסכון 15%</em></article><article><strong>קפה טחון עלית</strong><span>ויקטורי · רמת גן<br /><small>בתוקף: 01/09/2026–10/09/2026</small></span><b>₪19.90</b><em>חיסכון ₪4</em></article></div><small className="deals-preview-source">מקור: <a href="https://prices.shufersal.co.il/FileObject/" target="_blank" rel="noreferrer">שקיפות הרשתות</a> · <a href="https://data.gov.il/he/datasets/moital/price_controlled_consumer_products" target="_blank" rel="noreferrer">data.gov.il</a></small></div>; }

function DeepPreview() { return <><div className="deep-preview-note"><div className="deep-preview-header"><div><span className="compare-preview-eyebrow">השוואה מעמיקה</span><h2>חלב 3% תנובה 1 ליטר</h2><small>פירוק לפי חומרי גלם ורכיבים</small></div><span className="compare-preview-save">3 רכיבים</span></div><div className="deep-preview-ingredients"><button type="button" className="is-selected"><strong>חלב טרי</strong><small>₪9.20 · 71%</small></button><button type="button"><strong>שומן חלב</strong><small>₪1.85 · 14%</small></button><button type="button"><strong>אריזה והובלה</strong><small>₪1.85 · 15%</small></button></div><div className="deep-preview-table-wrap"><table className="deep-preview-table"><thead><tr><th>רכיב</th><th>עלות משוערת</th><th>חלק מהמוצר</th><th>לעומת המחיר</th></tr></thead><tbody><tr><th>חלב טרי</th><td>₪9.20</td><td>71%</td><td className="is-cheaper">המרכיב המרכזי</td></tr><tr><th>שומן חלב</th><td>₪1.85</td><td>14%</td><td>מחיר חומר גלם</td></tr><tr><th>אריזה והובלה</th><td>₪1.85</td><td>15%</td><td>עלות נלווית</td></tr></tbody></table></div><p className="deep-preview-note">עלות חומרי הגלם היא הערכה חישובית; מחיר המדף הוא הנתון הרשמי.</p></div><div className="deep-extra-preview"><div className="price-graph-card"><div className="deep-preview-header"><div><span className="compare-preview-eyebrow">מחיר לאורך זמן</span><h3>חלב 3% · מגמת מחיר</h3></div><strong className="is-cheaper">↓ 8%</strong></div><div className="graph-range-buttons"><button className="is-active">יומי</button><button>חודשי</button><button>3 חודשים</button><button>שנה</button><button>5 שנים</button></div><svg className="price-graph" viewBox="0 0 520 150" role="img" aria-label="גרף מחיר"><path d="M20 112 L105 88 L190 98 L275 68 L360 78 L445 42 L500 53" fill="none" stroke="#218749" strokeWidth="5" strokeLinecap="round" /><path d="M20 112 L105 88 L190 98 L275 68 L360 78 L445 42 L500 53 L500 140 L20 140 Z" fill="rgba(33,135,73,.12)" /><line x1="20" y1="140" x2="500" y2="140" stroke="#9eafbf" /><circle cx="500" cy="53" r="7" fill="#218749" /></svg><div className="price-graph-labels"><span>מרץ</span><span>אפריל</span><span>מאי</span><span>יוני</span><span>יולי</span><span>אוגוסט</span></div></div></div></>; }

function ReceiptsPreview() { return <div className="receipts-preview"><div className="upload-list-card"><span className="compare-preview-eyebrow">קבלות ורשימות קניות</span><h2>העלה תמונה או מסמך</h2><p>המערכת תזהה את המוצרים, המחירים והתאריך. לאחר מכן תבחר מול איזו קבלה להשוות.</p><button type="button" className="btn btn--primary"><Icon name="upload" /> העלה קבלה או רשימה</button></div><div className="receipt-select-preview receipt-range-card"><strong>השוואה מול קבלות קודמות</strong><label><input type="radio" defaultChecked name="receipt-range" /> חודש אחרון</label><label><input type="radio" name="receipt-range" /> חודשיים</label><label><input type="radio" name="receipt-range" /> שנה</label><label><input type="radio" name="receipt-range" /> כל הקבלות</label></div><div className="receipts-list"><strong>הקבלות שלי</strong><button type="button"><span>05/09/2026 · רמי לוי · רמת גן</span><b>₪186.40</b></button><button type="button"><span>12/08/2026 · ויקטורי · רמת גן</span><b>₪204.90</b></button></div></div>; }

function ComparisonPreview() { return <><div className="compare-preview-search"><input aria-label="חיפוש מוצר להשוואה" placeholder="חפשו מוצר נוסף להשוואה…" /><button type="button"><Icon name="plus" /> הוסף</button></div><div className="compare-preview-heading"><div><span className="compare-preview-eyebrow">המוצר שנבחר</span><h2>חלב 3% תנובה 1 ליטר</h2><small>3 ספקים נמצאו · מיקום לפי דף הבית</small></div><span className="compare-preview-save"><Icon name="check" /> עד ₪2.00 חיסכון</span></div><div className="compare-preview-suppliers"><div className="chain-price-grid">{['רמי לוי · רמת גן','ויקטורי · רמת גן','קרפור · רמת גן'].map((name, index) => <article key={name} className={`chain-price-block ${index === 0 ? 'is-cheapest' : 'is-pricier'}`}><span className="chain-price-block__badge">{index === 0 ? '✓ הכי זול' : `יקר ב־₪${(index * 0.6).toFixed(2)}`}</span><h4>{name}</h4><strong className="chain-price-block__price">₪{(12.9 + index * 0.6).toFixed(2)}</strong><small>מחיר רשמי · עודכן היום</small></article>)}</div></div></>; }

export default function ComparePreview() { const [activeTab, setActiveTab] = useState('compare'); return <div className="app compare-preview-app"><IconSprite /><header className="app-header"><h1>SuperNav AI</h1><p className="app-tagline">מצב תצוגה מקדימה · נתוני הדגמה בלבד</p></header><main className="app-main"><div className="compare-hub"><h1 className="compare-hub__title">השוואת מחירים</h1><section className="compare-page compare-preview-page"><p className="compare-preview-label"><Icon name="tag" /> דמו עיצובי — המחירים כאן אינם נתונים חיים</p><div className="compare-hub__tabs" role="tablist" aria-label="סוג השוואה">{tabs.map((label, index) => <button key={label} type="button" className={activeTab === ['compare', 'deals', 'deep', 'history'][index] ? 'is-active' : ''} onClick={() => setActiveTab(['compare', 'deals', 'deep', 'history'][index])}><Icon name={icons[index]} /><span>{label}</span></button>)}</div>{activeTab === 'deals' ? <DealsPreview /> : activeTab === 'deep' ? <DeepPreview /> : activeTab === 'history' ? <ReceiptsPreview /> : <ComparisonPreview />}</section></div></main></div>; }
